name: EmbeddingShow
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - ld_impl_linux-64=2.43
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libmpdec=4.0.0
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.13.0
  - python_abi=3.13
  - readline=8.2
  - requests=2.32.3
  - tk=8.6.13
  - tzdata=2024b
  - urllib3=2.2.3
  - xz=5.2.6
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - attrs==24.2.0
      - frozenlist==1.5.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.4
      - langchain-core==0.3.13
      - langchain-text-splitters==0.3.0
      - langsmith==0.1.137
      - multidict==6.1.0
      - numpy==1.26.4
      - orjson==3.10.10
      - packaging==24.1
      - propcache==0.2.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyyaml==6.0.2
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.36
      - tenacity==9.0.0
      - typing-extensions==4.12.2
      - yarl==1.17.0
