name: EmbeddingShow
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - ld_impl_linux-64=2.43
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libmpdec=4.0.0
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.13.0
  - python_abi=3.13
  - readline=8.2
  - requests=2.32.3
  - tk=8.6.13
  - tzdata=2024b
  - urllib3=2.2.3
  - xz=5.2.6
  - zstandard=0.23.0
  - zstd=1.5.6
